# Generated by Django 5.0.2 on 2024-02-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representante_legal', models.CharField(max_length=20)),
                ('nombre_comercio', models.CharField(max_length=30)),
                ('fecha_apertura', models.DateField()),
            ],
        ),
    ]
